### GET request to example server
GET http://localhost:8080/api/v2/current-accounts
Accept: application/json

### GET all current accounts
GET http://localhost:8080/api/v2/current-accounts
Accept: application/json

### GET current account by iban
GET http://localhost:8080/api/v2/current-accounts/DE00000000000000010004
Accept: application/json

### Create a new CurrentAccount
POST http://localhost:8080/api/v2/current-accounts
Accept: application/json
Content-Type: application/json

{
  "ownerId": 1,
  "overdraftInterestRate": 0.0,
  "overdraftLimit": 0.0
}

### Update a CurrentAccount
PUT http://localhost:8080/api/v2/current-accounts/DE10001
Accept: application/json
Content-Type: application/json

{
  "ownerId": 1,
  "overdraftInterestRate": 10.0,
  "overdraftLimit": 1000.0
}

### Delete a current account
DELETE http://localhost:8080/api/v2/current-accounts/DE00000000000000010002
